trigger:
  - main

name: Playwright

pool:
  name: "Scale Set Build Agents"

container: mcr.microsoft.com/playwright:bionic

steps:
  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: "ci"

  - task: Npm@1
    inputs:
      command: custom
      customCommand: "run install:playwright"
  - script: |
      npm run test:e2e -- --project chromium
